import { SignInButton } from '@clerk/nextjs'
import { useAtomValue } from 'jotai'
import Head from 'next/head'
import Sidebar from '~/components/Sidebar/Sidebar'
import { expandedAtom } from '~/components/atoms'
import { api } from '~/utils/api'

export default function Home() {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' })

  const expanded = useAtomValue(expandedAtom)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Sidebar />

      <div className={`text-xl ${expanded ? 'ml-56' : 'ml-16'}`}>
        <h1>Hello There</h1>
        <SignInButton />
      </div>
    </>
  )
}
